CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250303201411_FirstProjectMigration') THEN
    CREATE TABLE users (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        name VARCHAR(60) NOT NULL,
        email VARCHAR(60) NOT NULL,
        user_name VARCHAR(30) NOT NULL,
        password VARCHAR(30) NOT NULL,
        created timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
        CONSTRAINT "PK_users" PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250303201411_FirstProjectMigration') THEN
    CREATE TABLE wallets (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        balance numeric NOT NULL DEFAULT 0.0,
        "UserId" integer NOT NULL,
        created timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
        CONSTRAINT "PK_wallets" PRIMARY KEY (id),
        CONSTRAINT "FK_wallets_users_UserId" FOREIGN KEY ("UserId") REFERENCES users (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250303201411_FirstProjectMigration') THEN
    CREATE TABLE transactions (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        amount numeric NOT NULL DEFAULT 0.0,
        type text NOT NULL,
        "WalletId" integer NOT NULL,
        "TargetWalletId" integer,
        created timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
        CONSTRAINT "PK_transactions" PRIMARY KEY (id),
        CONSTRAINT "FK_transactions_wallets_TargetWalletId" FOREIGN KEY ("TargetWalletId") REFERENCES wallets (id),
        CONSTRAINT "FK_transactions_wallets_WalletId" FOREIGN KEY ("WalletId") REFERENCES wallets (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250303201411_FirstProjectMigration') THEN
    CREATE INDEX "IX_transactions_TargetWalletId" ON transactions ("TargetWalletId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250303201411_FirstProjectMigration') THEN
    CREATE INDEX "IX_transactions_WalletId" ON transactions ("WalletId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250303201411_FirstProjectMigration') THEN
    CREATE INDEX idx_users_email ON users (email);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250303201411_FirstProjectMigration') THEN
    CREATE UNIQUE INDEX "IX_wallets_UserId" ON wallets ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250303201411_FirstProjectMigration') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20250303201411_FirstProjectMigration', '9.0.2');
    END IF;
END $EF$;
COMMIT;

